<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('cities')->insert(["name" => "Recife", 'ibge_cod' => "2611606",'state_id' => '1','slug' => Str::slug('Recife'),],);
        DB::table('cities')->insert(["name" => "Abreu e Lima", 'ibge_cod' => "2600054",'state_id' => '1','slug' => Str::slug('Abreu e Lima'),],);
        DB::table('cities')->insert(["name" => "Afogados da Ingazeira", 'ibge_cod' => "2600104",'state_id' => '1','slug' => Str::slug('Afogados da Ingazeira'),],);
        DB::table('cities')->insert(["name" => "Afrânio", 'ibge_cod' => "2600203",'state_id' => '1','slug' => Str::slug('Afrânio'),],);
        DB::table('cities')->insert(["name" => "Agrestina", 'ibge_cod' => "2600302",'state_id' => '1','slug' => Str::slug('Agrestina'),],);
        DB::table('cities')->insert(["name" => "Água Preta", 'ibge_cod' => "2600401",'state_id' => '1','slug' => Str::slug('Água Preta'),],);
        DB::table('cities')->insert(["name" => "Águas Belas", 'ibge_cod' => "2600500",'state_id' => '1','slug' => Str::slug('Águas Belas'),],);
        DB::table('cities')->insert(["name" => "Alagoinha", 'ibge_cod' => "2600609",'state_id' => '1','slug' => Str::slug('Alagoinha'),],);
        DB::table('cities')->insert(["name" => "Aliança", 'ibge_cod' => "2600708",'state_id' => '1','slug' => Str::slug('Aliança'),],);
        DB::table('cities')->insert(["name" => "Altinho", 'ibge_cod' => "2600807",'state_id' => '1','slug' => Str::slug('Altinho'),],);
        DB::table('cities')->insert(["name" => "Amaraji", 'ibge_cod' => "2600906",'state_id' => '1','slug' => Str::slug('Amaraji'),],);
        DB::table('cities')->insert(["name" => "Angelim", 'ibge_cod' => "2601003",'state_id' => '1','slug' => Str::slug('Angelim'),],);
        DB::table('cities')->insert(["name" => "Araçoiaba", 'ibge_cod' => "2601052",'state_id' => '1','slug' => Str::slug('Araçoiaba'),],);
        DB::table('cities')->insert(["name" => "Araripina", 'ibge_cod' => "2601102",'state_id' => '1','slug' => Str::slug('Araripina'),],);
        DB::table('cities')->insert(["name" => "Arcoverde", 'ibge_cod' => "2601201",'state_id' => '1','slug' => Str::slug('Arcoverde'),],);
        DB::table('cities')->insert(["name" => "Barra de Guabiraba", 'ibge_cod' => "2601300",'state_id' => '1','slug' => Str::slug('Barra de Guabiraba'),],);
        DB::table('cities')->insert(["name" => "Barreiros", 'ibge_cod' => "2601409",'state_id' => '1','slug' => Str::slug('Barreiros'),],);
        DB::table('cities')->insert(["name" => "Belém de Maria", 'ibge_cod' => "2601508",'state_id' => '1','slug' => Str::slug('Belém de Maria'),],);
        DB::table('cities')->insert(["name" => "Belém do São Francisco", 'ibge_cod' => "2601607",'state_id' => '1','slug' => Str::slug('Belém do São Francisco'),],);
        DB::table('cities')->insert(["name" => "Belo Jardim", 'ibge_cod' => "2601706",'state_id' => '1','slug' => Str::slug('Belo Jardim'),],);
        DB::table('cities')->insert(["name" => "Betânia", 'ibge_cod' => "2601805",'state_id' => '1','slug' => Str::slug('Betânia'),],);
        DB::table('cities')->insert(["name" => "Bezerros", 'ibge_cod' => "2601904",'state_id' => '1','slug' => Str::slug('Bezerros'),],);
        DB::table('cities')->insert(["name" => "Bodocó", 'ibge_cod' => "2602001",'state_id' => '1','slug' => Str::slug('Bodocó'),],);
        DB::table('cities')->insert(["name" => "Bom Conselho", 'ibge_cod' => "2602100",'state_id' => '1','slug' => Str::slug('Bom Conselho'),],);
        DB::table('cities')->insert(["name" => "Bom Jardim", 'ibge_cod' => "2602209",'state_id' => '1','slug' => Str::slug('Bom Jardim'),],);
        DB::table('cities')->insert(["name" => "Bonito", 'ibge_cod' => "2602308",'state_id' => '1','slug' => Str::slug('Bonito'),],);
        DB::table('cities')->insert(["name" => "Brejão", 'ibge_cod' => "2602407",'state_id' => '1','slug' => Str::slug('Brejão'),],);
        DB::table('cities')->insert(["name" => "Brejinho", 'ibge_cod' => "2602506",'state_id' => '1','slug' => Str::slug('Brejinho'),],);
        DB::table('cities')->insert(["name" => "Brejo da Madre de Deus", 'ibge_cod' => "2602605",'state_id' => '1','slug' => Str::slug('Brejo da Madre de Deus'),],);
        DB::table('cities')->insert(["name" => "Buenos Aires", 'ibge_cod' => "2602704",'state_id' => '1','slug' => Str::slug('Buenos Aires'),],);
        DB::table('cities')->insert(["name" => "Buíque", 'ibge_cod' => "2602803",'state_id' => '1','slug' => Str::slug('Buíque'),],);
        DB::table('cities')->insert(["name" => "Cabo de Santo Agostinho", 'ibge_cod' => "2602902",'state_id' => '1','slug' => Str::slug('Cabo de Santo Agostinho'),],);
        DB::table('cities')->insert(["name" => "Cabrobó", 'ibge_cod' => "2603009",'state_id' => '1','slug' => Str::slug('Cabrobó'),],);
        DB::table('cities')->insert(["name" => "Cachoeirinha", 'ibge_cod' => "2603108",'state_id' => '1','slug' => Str::slug('Cachoeirinha'),],);
        DB::table('cities')->insert(["name" => "Caetés", 'ibge_cod' => "2603207",'state_id' => '1','slug' => Str::slug('Caetés'),],);
        DB::table('cities')->insert(["name" => "Calçado", 'ibge_cod' => "2603306",'state_id' => '1','slug' => Str::slug('Calçado'),],);
        DB::table('cities')->insert(["name" => "Calumbi", 'ibge_cod' => "2603405",'state_id' => '1','slug' => Str::slug('Calumbi'),],);
        DB::table('cities')->insert(["name" => "Camaragibe", 'ibge_cod' => "2603454",'state_id' => '1','slug' => Str::slug('Camaragibe'),],);
        DB::table('cities')->insert(["name" => "Camocim de São Félix", 'ibge_cod' => "2603504",'state_id' => '1','slug' => Str::slug('Camocim de São Félix'),],);
        DB::table('cities')->insert(["name" => "Camutanga", 'ibge_cod' => "2603603",'state_id' => '1','slug' => Str::slug('Camutanga'),],);
        DB::table('cities')->insert(["name" => "Canhotinho", 'ibge_cod' => "2603702",'state_id' => '1','slug' => Str::slug('Canhotinho'),],);
        DB::table('cities')->insert(["name" => "Capoeiras", 'ibge_cod' => "2603801",'state_id' => '1','slug' => Str::slug('Capoeiras'),],);
        DB::table('cities')->insert(["name" => "Carnaíba", 'ibge_cod' => "2603900",'state_id' => '1','slug' => Str::slug('Carnaíba'),],);
        DB::table('cities')->insert(["name" => "Carnaubeira da Penha", 'ibge_cod' => "2603926",'state_id' => '1','slug' => Str::slug('Carnaubeira da Penha'),],);
        DB::table('cities')->insert(["name" => "Carpina", 'ibge_cod' => "2604007",'state_id' => '1','slug' => Str::slug('Carpina'),],);
        DB::table('cities')->insert(["name" => "Caruaru", 'ibge_cod' => "2604106",'state_id' => '1','slug' => Str::slug('Caruaru'),],);
        DB::table('cities')->insert(["name" => "Casinhas", 'ibge_cod' => "2604155",'state_id' => '1','slug' => Str::slug('Casinhas'),],);
        DB::table('cities')->insert(["name" => "Catende", 'ibge_cod' => "2604205",'state_id' => '1','slug' => Str::slug('Catende'),],);
        DB::table('cities')->insert(["name" => "Cedro", 'ibge_cod' => "2604304",'state_id' => '1','slug' => Str::slug('Cedro'),],);
        DB::table('cities')->insert(["name" => "Chã de Alegria", 'ibge_cod' => "2604403",'state_id' => '1','slug' => Str::slug('Chã de Alegria'),],);
        DB::table('cities')->insert(["name" => "Chã Grande", 'ibge_cod' => "2604502",'state_id' => '1','slug' => Str::slug('Chã Grande'),],);
        DB::table('cities')->insert(["name" => "Condado", 'ibge_cod' => "2604601",'state_id' => '1','slug' => Str::slug('Condado'),],);
        DB::table('cities')->insert(["name" => "Correntes", 'ibge_cod' => "2604700",'state_id' => '1','slug' => Str::slug('Correntes'),],);
        DB::table('cities')->insert(["name" => "Cortês", 'ibge_cod' => "2604809",'state_id' => '1','slug' => Str::slug('Cortês'),],);
        DB::table('cities')->insert(["name" => "Cumaru", 'ibge_cod' => "2604908",'state_id' => '1','slug' => Str::slug('Cumaru'),],);
        DB::table('cities')->insert(["name" => "Cupira", 'ibge_cod' => "2605004",'state_id' => '1','slug' => Str::slug('Cupira'),],);
        DB::table('cities')->insert(["name" => "Custódia", 'ibge_cod' => "2605103",'state_id' => '1','slug' => Str::slug('Custódia'),],);
        DB::table('cities')->insert(["name" => "Dormentes", 'ibge_cod' => "2605152",'state_id' => '1','slug' => Str::slug('Dormentes'),],);
        DB::table('cities')->insert(["name" => "Escada", 'ibge_cod' => "2605202",'state_id' => '1','slug' => Str::slug('Escada'),],);
        DB::table('cities')->insert(["name" => "Exu", 'ibge_cod' => "2605301",'state_id' => '1','slug' => Str::slug('Exu'),],);
        DB::table('cities')->insert(["name" => "Feira Nova", 'ibge_cod' => "2605400",'state_id' => '1','slug' => Str::slug('Feira Nova'),],);
        DB::table('cities')->insert(["name" => "Fernando de Noronha", 'ibge_cod' => "2605459",'state_id' => '1','slug' => Str::slug('Fernando de Noronha'),],);
        DB::table('cities')->insert(["name" => "Ferreiros", 'ibge_cod' => "2605509",'state_id' => '1','slug' => Str::slug('Ferreiros'),],);
        DB::table('cities')->insert(["name" => "Flores", 'ibge_cod' => "2605608",'state_id' => '1','slug' => Str::slug('Flores'),],);
        DB::table('cities')->insert(["name" => "Floresta", 'ibge_cod' => "2605707",'state_id' => '1','slug' => Str::slug('Floresta'),],);
        DB::table('cities')->insert(["name" => "Frei Miguelinho", 'ibge_cod' => "2605806",'state_id' => '1','slug' => Str::slug('Frei Miguelinho'),],);
        DB::table('cities')->insert(["name" => "Gameleira", 'ibge_cod' => "2605905",'state_id' => '1','slug' => Str::slug('Gameleira'),],);
        DB::table('cities')->insert(["name" => "Garanhuns", 'ibge_cod' => "2606002",'state_id' => '1','slug' => Str::slug('Garanhuns'),],);
        DB::table('cities')->insert(["name" => "Glória do Goitá", 'ibge_cod' => "2606101",'state_id' => '1','slug' => Str::slug('Glória do Goitá'),],);
        DB::table('cities')->insert(["name" => "Goiana", 'ibge_cod' => "2606200",'state_id' => '1','slug' => Str::slug('Goiana'),],);
        DB::table('cities')->insert(["name" => "Granito", 'ibge_cod' => "2606309",'state_id' => '1','slug' => Str::slug('Granito'),],);
        DB::table('cities')->insert(["name" => "Gravatá", 'ibge_cod' => "2606408",'state_id' => '1','slug' => Str::slug('Gravatá'),],);
        DB::table('cities')->insert(["name" => "Iati", 'ibge_cod' => "2606507",'state_id' => '1','slug' => Str::slug('Iati'),],);
        DB::table('cities')->insert(["name" => "Ibimirim", 'ibge_cod' => "2606606",'state_id' => '1','slug' => Str::slug('Ibimirim'),],);
        DB::table('cities')->insert(["name" => "Ibirajuba", 'ibge_cod' => "2606705",'state_id' => '1','slug' => Str::slug('Ibirajuba'),],);
        DB::table('cities')->insert(["name" => "Igarassu", 'ibge_cod' => "2606804",'state_id' => '1','slug' => Str::slug('Igarassu'),],);
        DB::table('cities')->insert(["name" => "Iguaraci", 'ibge_cod' => "2606903",'state_id' => '1','slug' => Str::slug('Iguaraci'),],);
        DB::table('cities')->insert(["name" => "Ilha de Itamaracá", 'ibge_cod' => "2607604",'state_id' => '1','slug' => Str::slug('Ilha de Itamaracá'),],);
        DB::table('cities')->insert(["name" => "Inajá", 'ibge_cod' => "2607000",'state_id' => '1','slug' => Str::slug('Inajá'),],);
        DB::table('cities')->insert(["name" => "Ingazeira", 'ibge_cod' => "2607109",'state_id' => '1','slug' => Str::slug('Ingazeira'),],);
        DB::table('cities')->insert(["name" => "Ipojuca", 'ibge_cod' => "2607208",'state_id' => '1','slug' => Str::slug('Ipojuca'),],);
        DB::table('cities')->insert(["name" => "Ipubi", 'ibge_cod' => "2607307",'state_id' => '1','slug' => Str::slug('Ipubi'),],);
        DB::table('cities')->insert(["name" => "Itacuruba", 'ibge_cod' => "2607406",'state_id' => '1','slug' => Str::slug('Itacuruba'),],);
        DB::table('cities')->insert(["name" => "Itaíba", 'ibge_cod' => "2607505",'state_id' => '1','slug' => Str::slug('Itaíba'),],);
        DB::table('cities')->insert(["name" => "Itambé", 'ibge_cod' => "2607653",'state_id' => '1','slug' => Str::slug('Itambé'),],);
        DB::table('cities')->insert(["name" => "Itapetim", 'ibge_cod' => "2607703",'state_id' => '1','slug' => Str::slug('Itapetim'),],);
        DB::table('cities')->insert(["name" => "Itapissuma", 'ibge_cod' => "2607752",'state_id' => '1','slug' => Str::slug('Itapissuma'),],);
        DB::table('cities')->insert(["name" => "Itaquitinga", 'ibge_cod' => "2607802",'state_id' => '1','slug' => Str::slug('Itaquitinga'),],);
        DB::table('cities')->insert(["name" => "Jaboatão dos Guararapes", 'ibge_cod' => "2607901",'state_id' => '1','slug' => Str::slug('Jaboatão dos Guararapes'),],);
        DB::table('cities')->insert(["name" => "Jaqueira", 'ibge_cod' => "2607950",'state_id' => '1','slug' => Str::slug('Jaqueira'),],);
        DB::table('cities')->insert(["name" => "Jataúba", 'ibge_cod' => "2608008",'state_id' => '1','slug' => Str::slug('Jataúba'),],);
        DB::table('cities')->insert(["name" => "Jatobá", 'ibge_cod' => "2608057",'state_id' => '1','slug' => Str::slug('Jatobá'),],);
        DB::table('cities')->insert(["name" => "João Alfredo", 'ibge_cod' => "2608107",'state_id' => '1','slug' => Str::slug('João Alfredo'),],);
        DB::table('cities')->insert(["name" => "Joaquim Nabuco", 'ibge_cod' => "2608206",'state_id' => '1','slug' => Str::slug('Joaquim Nabuco'),],);
        DB::table('cities')->insert(["name" => "Jucati", 'ibge_cod' => "2608255",'state_id' => '1','slug' => Str::slug('Jucati'),],);
        DB::table('cities')->insert(["name" => "Jupi", 'ibge_cod' => "2608305",'state_id' => '1','slug' => Str::slug('Jupi'),],);
        DB::table('cities')->insert(["name" => "Jurema", 'ibge_cod' => "2608404",'state_id' => '1','slug' => Str::slug('Jurema'),],);
        DB::table('cities')->insert(["name" => "Lagoa de Itaenga", 'ibge_cod' => "2608453",'state_id' => '1','slug' => Str::slug('Lagoa de Itaenga'),],);
        DB::table('cities')->insert(["name" => "Lagoa do Carro", 'ibge_cod' => "2608503",'state_id' => '1','slug' => Str::slug('Lagoa do Carro'),],);
        DB::table('cities')->insert(["name" => "Lagoa do Ouro", 'ibge_cod' => "2608602",'state_id' => '1','slug' => Str::slug('Lagoa do Ouro'),],);
        DB::table('cities')->insert(["name" => "Lagoa dos Gatos", 'ibge_cod' => "2608701",'state_id' => '1','slug' => Str::slug('Lagoa dos Gatos'),],);
        DB::table('cities')->insert(["name" => "Lagoa Grande", 'ibge_cod' => "2608750",'state_id' => '1','slug' => Str::slug('Lagoa Grande'),],);
        DB::table('cities')->insert(["name" => "Lajedo", 'ibge_cod' => "2608800",'state_id' => '1','slug' => Str::slug('Lajedo'),],);
        DB::table('cities')->insert(["name" => "Limoeiro", 'ibge_cod' => "2608909",'state_id' => '1','slug' => Str::slug('Limoeiro'),],);
        DB::table('cities')->insert(["name" => "Macaparana", 'ibge_cod' => "2609006",'state_id' => '1','slug' => Str::slug('Macaparana'),],);
        DB::table('cities')->insert(["name" => "Machados", 'ibge_cod' => "2609105",'state_id' => '1','slug' => Str::slug('Machados'),],);
        DB::table('cities')->insert(["name" => "Manari", 'ibge_cod' => "2609154",'state_id' => '1','slug' => Str::slug('Manari'),],);
        DB::table('cities')->insert(["name" => "Maraial", 'ibge_cod' => "2609204",'state_id' => '1','slug' => Str::slug('Maraial'),],);
        DB::table('cities')->insert(["name" => "Mirandiba", 'ibge_cod' => "2609303",'state_id' => '1','slug' => Str::slug('Mirandiba'),],);
        DB::table('cities')->insert(["name" => "Moreilândia", 'ibge_cod' => "2614303",'state_id' => '1','slug' => Str::slug('Moreilândia'),],);
        DB::table('cities')->insert(["name" => "Moreno", 'ibge_cod' => "2609402",'state_id' => '1','slug' => Str::slug('Moreno'),],);
        DB::table('cities')->insert(["name" => "Nazaré da Mata", 'ibge_cod' => "2609501",'state_id' => '1','slug' => Str::slug('Nazaré da Mata'),],);
        DB::table('cities')->insert(["name" => "Olinda", 'ibge_cod' => "2609600",'state_id' => '1','slug' => Str::slug('Olinda'),],);
        DB::table('cities')->insert(["name" => "Orobó", 'ibge_cod' => "2609709",'state_id' => '1','slug' => Str::slug('Orobó'),],);
        DB::table('cities')->insert(["name" => "Orocó", 'ibge_cod' => "2609808",'state_id' => '1','slug' => Str::slug('Orocó'),],);
        DB::table('cities')->insert(["name" => "Ouricuri", 'ibge_cod' => "2609907",'state_id' => '1','slug' => Str::slug('Ouricuri'),],);
        DB::table('cities')->insert(["name" => "Palmares", 'ibge_cod' => "2610004",'state_id' => '1','slug' => Str::slug('Palmares'),],);
        DB::table('cities')->insert(["name" => "Palmeirina", 'ibge_cod' => "2610103",'state_id' => '1','slug' => Str::slug('Palmeirina'),],);
        DB::table('cities')->insert(["name" => "Panelas", 'ibge_cod' => "2610202",'state_id' => '1','slug' => Str::slug('Panelas'),],);
        DB::table('cities')->insert(["name" => "Paranatama", 'ibge_cod' => "2610301",'state_id' => '1','slug' => Str::slug('Paranatama'),],);
        DB::table('cities')->insert(["name" => "Parnamirim", 'ibge_cod' => "2610400",'state_id' => '1','slug' => Str::slug('Parnamirim'),],);
        DB::table('cities')->insert(["name" => "Passira", 'ibge_cod' => "2610509",'state_id' => '1','slug' => Str::slug('Passira'),],);
        DB::table('cities')->insert(["name" => "Paudalho", 'ibge_cod' => "2610608",'state_id' => '1','slug' => Str::slug('Paudalho'),],);
        DB::table('cities')->insert(["name" => "Paulista", 'ibge_cod' => "2610707",'state_id' => '1','slug' => Str::slug('Paulista'),],);
        DB::table('cities')->insert(["name" => "Pedra", 'ibge_cod' => "2610806",'state_id' => '1','slug' => Str::slug('Pedra'),],);
        DB::table('cities')->insert(["name" => "Pesqueira", 'ibge_cod' => "2610905",'state_id' => '1','slug' => Str::slug('Pesqueira'),],);
        DB::table('cities')->insert(["name" => "Petrolândia", 'ibge_cod' => "2611002",'state_id' => '1','slug' => Str::slug('Petrolândia'),],);
        DB::table('cities')->insert(["name" => "Petrolina", 'ibge_cod' => "2611101",'state_id' => '1','slug' => Str::slug('Petrolina'),],);
        DB::table('cities')->insert(["name" => "Poção", 'ibge_cod' => "2611200",'state_id' => '1','slug' => Str::slug('Poção'),],);
        DB::table('cities')->insert(["name" => "Pombos", 'ibge_cod' => "2611309",'state_id' => '1','slug' => Str::slug('Pombos'),],);
        DB::table('cities')->insert(["name" => "Primavera", 'ibge_cod' => "2611408",'state_id' => '1','slug' => Str::slug('Primavera'),],);
        DB::table('cities')->insert(["name" => "Quipapá", 'ibge_cod' => "2611507",'state_id' => '1','slug' => Str::slug('Quipapá'),],);
        DB::table('cities')->insert(["name" => "Quixaba", 'ibge_cod' => "2611533",'state_id' => '1','slug' => Str::slug('Quixaba'),],);
        DB::table('cities')->insert(["name" => "Riacho das Almas", 'ibge_cod' => "2611705",'state_id' => '1','slug' => Str::slug('Riacho das Almas'),],);
        DB::table('cities')->insert(["name" => "Ribeirão", 'ibge_cod' => "2611804",'state_id' => '1','slug' => Str::slug('Ribeirão'),],);
        DB::table('cities')->insert(["name" => "Rio Formoso", 'ibge_cod' => "2611903",'state_id' => '1','slug' => Str::slug('Rio Formoso'),],);
        DB::table('cities')->insert(["name" => "Sairé", 'ibge_cod' => "2612000",'state_id' => '1','slug' => Str::slug('Sairé'),],);
        DB::table('cities')->insert(["name" => "Salgadinho", 'ibge_cod' => "2612109",'state_id' => '1','slug' => Str::slug('Salgadinho'),],);
        DB::table('cities')->insert(["name" => "Salgueiro", 'ibge_cod' => "2612208",'state_id' => '1','slug' => Str::slug('Salgueiro'),],);
        DB::table('cities')->insert(["name" => "Saloá", 'ibge_cod' => "2612307",'state_id' => '1','slug' => Str::slug('Saloá'),],);
        DB::table('cities')->insert(["name" => "Sanharó", 'ibge_cod' => "2612406",'state_id' => '1','slug' => Str::slug('Sanharó'),],);
        DB::table('cities')->insert(["name" => "Santa Cruz", 'ibge_cod' => "2612455",'state_id' => '1','slug' => Str::slug('Santa Cruz'),],);
        DB::table('cities')->insert(["name" => "Santa Cruz da Baixa Verde", 'ibge_cod' => "2612471",'state_id' => '1','slug' => Str::slug('Santa Cruz da Baixa Verde'),],);
        DB::table('cities')->insert(["name" => "Santa Cruz do Capibaribe", 'ibge_cod' => "2612505",'state_id' => '1','slug' => Str::slug('Santa Cruz do Capibaribe'),],);
        DB::table('cities')->insert(["name" => "Santa Filomena", 'ibge_cod' => "2612554",'state_id' => '1','slug' => Str::slug('Santa Filomena'),],);
        DB::table('cities')->insert(["name" => "Santa Maria da Boa Vista", 'ibge_cod' => "2612604",'state_id' => '1','slug' => Str::slug('Santa Maria da Boa Vista'),],);
        DB::table('cities')->insert(["name" => "Santa Maria do Cambucá", 'ibge_cod' => "2612703",'state_id' => '1','slug' => Str::slug('Santa Maria do Cambucá'),],);
        DB::table('cities')->insert(["name" => "Santa Terezinha", 'ibge_cod' => "2612802",'state_id' => '1','slug' => Str::slug('Santa Terezinha'),],);
        DB::table('cities')->insert(["name" => "São Benedito do Sul", 'ibge_cod' => "2612901",'state_id' => '1','slug' => Str::slug('São Benedito do Sul'),],);
        DB::table('cities')->insert(["name" => "São Bento do Una", 'ibge_cod' => "2613008",'state_id' => '1','slug' => Str::slug('São Bento do Una'),],);
        DB::table('cities')->insert(["name" => "São Caetano", 'ibge_cod' => "2613107",'state_id' => '1','slug' => Str::slug('São Caetano'),],);
        DB::table('cities')->insert(["name" => "São João", 'ibge_cod' => "2613206",'state_id' => '1','slug' => Str::slug('São João'),],);
        DB::table('cities')->insert(["name" => "São Joaquim do Monte", 'ibge_cod' => "2613305",'state_id' => '1','slug' => Str::slug('São Joaquim do Monte'),],);
        DB::table('cities')->insert(["name" => "São José da Coroa Grande", 'ibge_cod' => "2613404",'state_id' => '1','slug' => Str::slug('São José da Coroa Grande'),],);
        DB::table('cities')->insert(["name" => "São José do Belmonte", 'ibge_cod' => "2613503",'state_id' => '1','slug' => Str::slug('São José do Belmonte'),],);
        DB::table('cities')->insert(["name" => "São José do Egito", 'ibge_cod' => "2613602",'state_id' => '1','slug' => Str::slug('São José do Egito'),],);
        DB::table('cities')->insert(["name" => "São Lourenço da Mata", 'ibge_cod' => "2613701",'state_id' => '1','slug' => Str::slug('São Lourenço da Mata'),],);
        DB::table('cities')->insert(["name" => "São Vicente Férrer", 'ibge_cod' => "2613800",'state_id' => '1','slug' => Str::slug('São Vicente Férrer'),],);
        DB::table('cities')->insert(["name" => "Serra Talhada", 'ibge_cod' => "2613909",'state_id' => '1','slug' => Str::slug('Serra Talhada'),],);
        DB::table('cities')->insert(["name" => "Serrita", 'ibge_cod' => "2614006",'state_id' => '1','slug' => Str::slug('Serrita'),],);
        DB::table('cities')->insert(["name" => "Sertânia", 'ibge_cod' => "2614105",'state_id' => '1','slug' => Str::slug('Sertânia'),],);
        DB::table('cities')->insert(["name" => "Sirinhaém", 'ibge_cod' => "2614204",'state_id' => '1','slug' => Str::slug('Sirinhaém'),],);
        DB::table('cities')->insert(["name" => "Solidão", 'ibge_cod' => "2614402",'state_id' => '1','slug' => Str::slug('Solidão'),],);
        DB::table('cities')->insert(["name" => "Surubim", 'ibge_cod' => "2614501",'state_id' => '1','slug' => Str::slug('Surubim'),],);
        DB::table('cities')->insert(["name" => "Tabira", 'ibge_cod' => "2614600",'state_id' => '1','slug' => Str::slug('Tabira'),],);
        DB::table('cities')->insert(["name" => "Tacaimbó", 'ibge_cod' => "2614709",'state_id' => '1','slug' => Str::slug('Tacaimbó'),],);
        DB::table('cities')->insert(["name" => "Tacaratu", 'ibge_cod' => "2614808",'state_id' => '1','slug' => Str::slug('Tacaratu'),],);
        DB::table('cities')->insert(["name" => "Tamandaré", 'ibge_cod' => "2614857",'state_id' => '1','slug' => Str::slug('Tamandaré'),],);
        DB::table('cities')->insert(["name" => "Taquaritinga do Norte", 'ibge_cod' => "2615003",'state_id' => '1','slug' => Str::slug('Taquaritinga do Norte'),],);
        DB::table('cities')->insert(["name" => "Terezinha", 'ibge_cod' => "2615102",'state_id' => '1','slug' => Str::slug('Terezinha'),],);
        DB::table('cities')->insert(["name" => "Terra Nova", 'ibge_cod' => "2615201",'state_id' => '1','slug' => Str::slug('Terra Nova'),],);
        DB::table('cities')->insert(["name" => "Timbaúba", 'ibge_cod' => "2615300",'state_id' => '1','slug' => Str::slug('Timbaúba'),],);
        DB::table('cities')->insert(["name" => "Toritama", 'ibge_cod' => "2615409",'state_id' => '1','slug' => Str::slug('Toritama'),],);
        DB::table('cities')->insert(["name" => "Tracunhaém", 'ibge_cod' => "2615508",'state_id' => '1','slug' => Str::slug('Tracunhaém'),],);
        DB::table('cities')->insert(["name" => "Trindade", 'ibge_cod' => "2615607",'state_id' => '1','slug' => Str::slug('Trindade'),],);
        DB::table('cities')->insert(["name" => "Triunfo", 'ibge_cod' => "2615706",'state_id' => '1','slug' => Str::slug('Triunfo'),],);
        DB::table('cities')->insert(["name" => "Tupanatinga", 'ibge_cod' => "2615805",'state_id' => '1','slug' => Str::slug('Tupanatinga'),],);
        DB::table('cities')->insert(["name" => "Tuparetama", 'ibge_cod' => "2615904",'state_id' => '1','slug' => Str::slug('Tuparetama'),],);
        DB::table('cities')->insert(["name" => "Venturosa", 'ibge_cod' => "2616001",'state_id' => '1','slug' => Str::slug('Venturosa'),],);
        DB::table('cities')->insert(["name" => "Verdejante", 'ibge_cod' => "2616100",'state_id' => '1','slug' => Str::slug('Verdejante'),],);
        DB::table('cities')->insert(["name" => "Vertente do Lério", 'ibge_cod' => "2616183",'state_id' => '1','slug' => Str::slug('Vertente do Lério'),],);
        DB::table('cities')->insert(["name" => "Vertentes", 'ibge_cod' => "2616209",'state_id' => '1','slug' => Str::slug('Vertentes'),],);
        DB::table('cities')->insert(["name" => "Vicência", 'ibge_cod' => "2616308",'state_id' => '1','slug' => Str::slug('Vicência'),],);
        DB::table('cities')->insert(["name" => "Vitória de Santo Antão", 'ibge_cod' => "2616407",'state_id' => '1','slug' => Str::slug('Vitória de Santo Antão'),],);
        DB::table('cities')->insert(["name" => "Xexéu", 'ibge_cod' => "2616506",'state_id' => '1','slug' => Str::slug('Xexéu'),],);
    }
}
